### ISSUE TITLE
t/session-mongodb.t fails

### ISSUE THREAD

**Issue by eserte** [SysPete/Dancer2-Plugin-PageHistory#3]
With Dancer2-Plugin-PageHistory-0.206 I see the following test error:
```
...
MongoDB::SelectionError: No readable server available for matching read preference primary. MongoDB server status:
Topology type: Single; Member status:
  localhost:27017 (type: Unknown, error: MongoDB::NetworkError: Could not connect to 'localhost:27017': Connection refused )
t/session-mongodb.t ..... 
Dubious, test returned 61 (wstat 15616, 0x3d00)
No subtests run 
```

Probably this happens only if there's no local mongodb running, and if a rather new MongoDB.pm (i.e. v1) is installed. AFAIK the new MongoDB driver does lazy connects, so just constructing the MongoDB::Client object is not enough to check for the availability of a MongoDB server.

**Comment by SysPete** [comment]
Thanks @eserte
